// resources/js/UI/Results.tsx
import React from 'react'

interface ResultsProp {
    results: Array<{
        id: number,
        url: string,
        title: string,
        site: { domain: string },
        page: { url: string, title: string }
    }>
}
interface ResultsState { }

export default class Results extends React.Component<ResultsProp, ResultsState> {
    render(): React.ReactNode {
        return <ul className="flex flex-wrap">
            {this.props.results.map(result => {
                return <li className="w-full md:w-1/4 p-2" key={result.id.toString()}>
                    <a className="cursor-pointer" href={result.page.url} target="_blank">
                        <img className="w-full" src={result.url} alt={result.title} width="300" height="300" />
                    </a>
                    <div>
                        <a className="block p-1 underline cursor-pointer hover:no-underline font-bold" href={result.page.url} target="_blank">
                            {result.page.title}
                        </a>
                        <a className="block p-1 underline cursor-pointer hover:no-underline text-sm text-gray-50" href={'https://' + result.site.domain} target="_blank">
                            {result.site.domain}
                        </a>
                    </div>
                </li>
            })}
        </ul>

    }
}

// src/lib/ui/Results.svelte
<script lang="ts">
    export let results: Array<Result>;
</script>

<ul class="flex flex-wrap">
    {#each results as result (result.id)}
        <li class="w-full md:w-1/4 p-2">
            <a class="cursor-pointer" href={result.page.url} target="_blank">
                <img class="w-full" src={result.url} alt={result.title} width="300" height="300" />
            </a>
            <div>
                <a
                    class="block p-1 underline cursor-pointer hover:no-underline font-bold"
                    href={result.page.url}
                    target="_blank"
                >
                    {result.page.title}
                </a>
                <a
                    class="block p-1 underline cursor-pointer hover:no-underline text-sm text-gray-50"
                    href={"https://" + result.site.domain}
                    target="_blank"
                >
                    {result.site.domain}
                </a>
            </div>
        </li>
    {/each}
</ul>
