// resources/js/UI/Forms/Search.tsx
import React, { RefObject } from "react";

interface SearchProps {
    term: string,
    searchHandler: Function
}
interface SearchState { }

export default class Search extends React.Component<SearchProps, SearchState> {
    inputRef: RefObject<HTMLInputElement>;

    constructor(props: SearchProps) {
        super(props)

        this.search = this.search.bind(this);
        this.inputRef = React.createRef();
    }

    componentDidMount() {
        this.inputRef.current?.focus();
    }

    render() {
        return (
            <div>
                <div className="flex flex-col gap-4 text-center">
                    <label className="text-2xl" htmlFor="search">I want to find an image of...</label>
                    <div className="flex">
                        <input
                            className="p-4 text-stone-600 focus:shadow-lg focus:shadow-stone-600 flex-grow"
                            id="search"
                            ref={this.inputRef}
                            type="search"
                            placeholder=""
                            value={this.props.term}
                            onChange={this.search}
                            autoComplete="false"
                        />
                        <button
                            className="bg-stone-700 px-4 py-2 font-bold hover:bg-stone-500"
                            onClick={this.search}
                        >search</button>
                    </div>
                </div>
            </div>
        );
    }

    search(event: React.SyntheticEvent) {
        event.preventDefault()

        this.props.searchHandler(this.inputRef.current?.value)
    }
}

// src/lib/ui/Search.svelte
<script lang="ts">
    export let term: string = "";
    export let searchChange: Function;
    export let searchSelected: Function;
</script>

<div>
    <div class="flex flex-col gap-4 text-center">
        <label class="text-2xl" for="search">I want to find an image of...</label>
        <div class="flex gap-2">
            <input
                class="p-4 text-stone-600 focus:shadow-lg focus:shadow-stone-600 flex-grow"
                id="search"
                type="search"
                on:change={searchChange}
                value={term}
                autoComplete="false"
            />
            <button
                class="bg-yellow-300 text-stone-600 px-4 py-2 font-bold hover:bg-yellow-400"
                on:click={searchSelected}
            >
                search
            </button>
        </div>
    </div>
</div>
